# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

#   data flow
#
#   sys.tcl         str.tcl
#      |             |
#      '------.------'
#             v
#           log.tcl
#
package ifneeded tutils 1.0 [list apply {{dir} {
    foreach file {str.tcl sys.tcl log.tcl} {
        source [file join $dir $file]
    }
}} $dir]

